DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS trans;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE trans(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  transType BOOLEAN,
  name TEXT NOT NULL,
  amount FLOAT NOT NULL,
  dateDue DATE NOT NULL,
  frequency TEXT NOT NULL
);